"""Generate patcher/dll/strings_table.h for the dinput8 proxy: in-memory replacement of the CHS message
strings inside WO3U.exe (the file itself cannot be modified: SteamStub integrity check, Steam error 51).

usage: gen_dll_patch.py <build ver>     (the build whose LINKIDX_CHS.BIN / font the Korean bytes belong to)

Per row of translation_memory/exe_queue.jsonl + exe_ko.jsonl (all checked here, generation stops on any error):
  rva      file offset mapped through the section table of the original exe (e.g. 0xAC6068 -> 0xAC7868)
  expect   original CHS bytes + NUL (the DLL compares memory against this before writing)
  repl     Korean bytes (current ko_charset = the mapping of the build's font) zero-padded to the slot
  checks   Korean + NUL fits the slot; ESC colour codes identical and in order; %s/%w/%d multiset identical;
           leading two-digit message code kept; every character encodable
The table also carries the CRC32 and size of the build's LINKIDX_CHS.BIN; the DLL refuses to patch when the
installed index differs (Korean bytes would not match the installed font mapping).
"""
import collections, json, re, struct, sys, zlib, hashlib
from pathlib import Path
from ko_encode import encode

ROOT = Path(__file__).resolve().parents[1]
ORIG = ROOT / "backup/original/WO3U.exe"
OUT = ROOT / "patcher/dll/strings_table.h"
ESC = re.compile(r"⟨E⟩(?:C\d|R)")
FMT = re.compile(r"%\d*[sdw]")


def sections(d):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    n = struct.unpack_from("<H", d, pe + 6)[0]
    opt = struct.unpack_from("<H", d, pe + 20)[0]
    sec = pe + 24 + opt
    return [struct.unpack_from("<8sIIII", d, sec + i * 40) for i in range(n)]


def rva_of(secs, off):
    for name, vsize, va, rsize, roff in secs:
        if roff <= off < roff + rsize:
            return va + off - roff, name.rstrip(b"\0").decode()
    raise ValueError(hex(off))


def carr(b):
    return "{" + ",".join(f"0x{x:02x}" for x in b) + "}"


def main():
    ver = sys.argv[1]
    idx = (ROOT / "build" / ver / "LINKIDX_CHS.BIN").read_bytes()
    d = ORIG.read_bytes()
    secs = sections(d)
    q = {json.loads(l)["n"]: json.loads(l) for l in (ROOT / "translation_memory/exe_queue.jsonl").open(encoding="utf-8")}
    ko = {json.loads(l)["n"]: json.loads(l)["ko"] for l in (ROOT / "translation_memory/exe_ko.jsonl").open(encoding="utf-8") if l.strip()}
    errors, entries = [], []
    lines = ["/* generated by tools/gen_dll_patch.py - do not edit */",
             f"/* build {ver}; exe sha256 {hashlib.sha256(d).hexdigest()[:16]}; charset sha256 "
             f"{hashlib.sha256((ROOT / 'mapping/ko_charset.json').read_bytes()).hexdigest()[:16]} */",
             f"#define KR_IDX_SIZE {len(idx)}u", f"#define KR_IDX_CRC32 0x{zlib.crc32(idx):08x}u",
             "typedef struct { unsigned rva; unsigned elen; unsigned rlen; const unsigned char *expect; const unsigned char *repl; } KrPatch;"]
    for n in sorted(q):
        r, k = q[n], ko.get(n)
        if k is None:
            errors.append((n, "no translation")); continue
        if ESC.findall(r["jp"]) != ESC.findall(k) or ESC.findall(r["chs"]) != ESC.findall(k):
            errors.append((n, "colour codes", ESC.findall(r["chs"]), ESC.findall(k)))
        if collections.Counter(FMT.findall(r["jp"])) != collections.Counter(FMT.findall(k)):
            errors.append((n, "format tokens"))
        if r["chs"][:2].isdigit() and r["chs"][:2] != k[:2]:
            errors.append((n, "message code", r["chs"][:2], k[:2]))
        expect = d[r["off"]:r["off"] + r["chs_len"] + 1]
        if expect[:-1].decode("gbk") != r["chs"].replace("⟨E⟩", "\x1b") or expect[-1] != 0:
            errors.append((n, "exe bytes differ from queue"))
        new = encode(k.replace("⟨E⟩", "\x1b"))
        if len(new) + 1 > r["slot"]:
            errors.append((n, "does not fit", len(new) + 1, r["slot"]))
            continue
        repl = new + b"\0" * (r["slot"] - len(new))
        rva, sec = rva_of(secs, r["off"])
        if sec != ".rdata":
            errors.append((n, "not in .rdata", sec))
        lines.append(f"static const unsigned char e{n}[] = {carr(expect)};")
        lines.append(f"static const unsigned char r{n}[] = {carr(repl)};")
        entries.append(f"  {{0x{rva:x}, {len(expect)}, {len(repl)}, e{n}, r{n}}}, /* file 0x{r['off']:x} */")
    if errors:
        sys.exit(f"errors: {errors}")
    lines += ["static const KrPatch KR_PATCHES[] = {"] + entries + ["};", f"#define KR_PATCH_COUNT {len(entries)}"]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("wrote", OUT, len(entries), "entries, idx crc", f"{zlib.crc32(idx):08x}")
    print([e.split("/*")[1] + "->" + e.split(",")[0].strip(" {") for e in entries if "0xac6068" in e])


if __name__ == "__main__":
    main()
